services:
    db:
      image: mysql:latest
      container_name: wordpressdb
      restart: unless-stopped
      command: [
          '--mysql-native-password=ON',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci'
      ]
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - 3306:3306  
      environment:
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MYSQL_USER: "${DB_USER_NAME}"
        MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./web:/:web
        depends_on:
                - db    
    php:
        build:
            context: ./docker/config/php/
            dockerfile: Docker
        volumes:
            - ./docker/config/php/conf.d/php.ini:/usr/local/etc/php/conf.d/conf.ini
            - ./web:/web
volumes:
  db_data:            
